### ISSUE TITLE
hxu is not recognized as valid triage engineer

### ISSUE THREAD

**Issue by jensstutte** [mozilla/relman-auto-nag#1218]
On the DOM: LWS calendar next would be hxu@mozilla.com, but the bot does not want this:

The following calendar needs to be updated in order to have a triage owner:

    DOM:LWS: cannot find the following person:
        hxu

For jjalkanen (other new entry) this worked, so not sure what I am missing.

**Comment by marco-c** [comment]
I think this means hxu couldn't be found in people.mozilla.org (https://github.com/mozilla/relman-auto-nag/blob/ab5d64ae4f96607d98ec355c3cd7a83f69c8f371/auto_nag/people.py#L406)

@calixteman any idea why?

**Comment by jensstutte** [comment]
Maybe because a search for hxu gives 4 results there? Can/should I just use "Haiyang Xu" as name in the calendar?

**Comment by jensstutte** [comment]
Trying this ^ now.

**Comment by calixteman** [comment]
The "guess" is based on what we have in phonebook.
We try to be smart:
https://github.com/mozilla/relman-auto-nag/blob/ab5d64ae4f96607d98ec355c3cd7a83f69c8f371/auto_nag/people.py#L116
and I'd say that it likely fails to find something because `hxu` is very short.
So ideally, having the the same name as in phonebook should work fine.
