### ISSUE TITLE
Bug 1769486 detected as spam but wasn't marked as invalid

### ISSUE THREAD

**Issue by globau** [mozilla/relman-auto-nag#1438]
Received the following notification:

---
<p>The following bug is probably spam :
    <table style="border:1px solid black;border-collapse:collapse;" border="1">
      <thead>
        <tr>
          <th>Bug</th><th>Summary</th><th>Confidence (%)</th>
        </tr>
      </thead>
      <tbody>
        <tr bgcolor="#E0E0E0">
          <td>
            <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1769486">1769486</a>
          </td>
          <td>
            Not loading the web page http://landfill.bugzilla.org/
          </td>
          <td>
            99
          </td>
        </tr>
        </tbody>
    </table>
  </p>
---

However, the bug wasn't marked as spam by the bot.

**Comment by suhaibmujahid** [comment]
Thank you @globau for reporting this. The logs show that an error occurred while updating the bug on Bugzilla.

```
2022-05-16 06:17:37,408 - ERROR - spambug: Cannot put data for bug 1769486 (change => 
{
  "comment": {
    "body": "The [Bugbug](https://github.com/mozilla/bugbug/) bot thinks this bug is invalid.\nIf you think the bot is wrong, please reopen the bug and move it back to its prior component.\nIf your bug description is written in a non-English language, please use Google Translate or a similar service to translate it.\n\nPlease note that this is a production bug database used by the Mozilla community to develop Firefox, Thunderbird and other products.\nFiling test bugs here will waste the time of our contributors, volunteers and employees.\nAccounts that abuse bugzilla.mozilla.org will be disabled."
  },
  "product": "Invalid Bugs",
  "component": "General",
  "version": "unspecified",
  "milestone": "---",
  "status": "RESOLVED",
  "resolution": "INVALID"
}).
```

**Comment by marco-c** [comment]
Same happened for https://bugzilla.mozilla.org/show_bug.cgi?id=1771895:
2022-05-31 13:16:39,533 - ERROR - spambug: Cannot put data for bug 1771895 (change => {'comment': {'body': 'The [Bugbug](https://github.com/mozilla/bugbug/) bot thinks this bug is invalid.\nIf you think the bot is wrong, please reopen the bug and move it back to its prior component.\nIf your bug description is written in a non-English language, please use Google Translate or a similar service to translate it.\n\nPlease note that this is a production bug database used by the Mozilla community to develop Firefox, Thunderbird and other products.\nFiling test bugs here will waste the time of our contributors, volunteers and employees.\nAccounts that abuse bugzilla.mozilla.org will be disabled.'}, 'product': 'Invalid Bugs', 'component': 'General', 'version': 'unspecified', 'milestone': '---', 'status': 'RESOLVED', 'resolution': 'INVALID'}).

Probably they set some field that exists in the "Firefox" product but doesn't exist in the "Invalid Bugs" product, and so the move fails.
@globau is there any way to tell BZ to set all other fields to their default for the target product?

**Comment by marco-c** [comment]
Yep, moving through the UI works, https://bugzilla.mozilla.org/show_bug.cgi?id=1771895#a7071_420453, but it automatically resets status flags and Target Milestone.

**Comment by globau** [comment]
I'm not aware of any way to reset all fields to their default values.  As you discovered, Bugzilla itself relies on the user to select new values where required.

The JSON you're passing in, as provided in https://github.com/mozilla/relman-auto-nag/issues/1438#issuecomment-1142127626, is already resetting the "version" and "milestone" fields.  I suspect it's probably the tracking flags that triggered this as the initial bug also had them set.

Can bugbug automatically clear any tracking and status flags in addition to the version and milestone?

**Comment by globau** [comment]
Here's the logic that Bugzilla runs to detect fields with values that need touching when the product changes: https://github.com/mozilla-bteam/bmo/blob/fa9b3022b7650a80a55e599a7fafee151cac5f5f/extensions/BugModal/lib/WebService.pm#L197

Weirdly it doesn't check tracking/status flags; only components, milestones, versions, and groups.  What autonag is doing _should_ be sufficient.

@dklawren do you know what's going on here?

**Comment by marco-c** [comment]
I now found out I had filed https://bugzilla.mozilla.org/show_bug.cgi?id=1532985 about this problem.

**Comment by dklawren** [comment]
> I now found out I had filed [bugzilla.mozilla.org/show_bug.cgi?id=1532985](https://bugzilla.mozilla.org/show_bug.cgi?id=1532985) about this problem.

There is other things that the UI is doing which we would have to consider. Besides the version difference, there is also the possibility of component and milestones being different in the new product. Also the UI will show group check boxes if the enabled groups are different from one to the next. 

1) We have a /rest/configuration API endpoint that can be used to determine beforehand if the version is in the destination product or what the new choices are for each of the fields that vary.
2) I would be OK with adding a choose_defaults=1 option the bug update API endpoint which would choose the defaults for you but I would not want it to just do it without some extra parameter. The API has to remain stable and consistent and so this change would cause confusion. We would look at it for the next version of the API (v2). 
3) Also for 2), just choosing a default will not work for all products as 'unspecified' is not always present and for version specifically, there is no default value like for instance milestones has. Usually the UI just pre-selects the highest alphanumeric value in the option list for version when entering a new bug.
