### ISSUE TITLE
Automatic cleanup of DUPLICATE bugs

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#225]
We can do a few things:
- [ ] Copy the signatures from the bug resolved as DUPLICATE to the bug it has been duplicated to (#184)
- [ ] Update the component of the DUPLICATE bug making it the same as the bug it has been duplicated to

**Comment by lizzard** [comment]
I had some similar ideas -- 
1.  Look for bugs  (recently) marked DUPLICATE and their originals.
2. If the original is marked fixed or verified for status-firefoxXX, then mark status-firefoxXX fixed in the duplicate.  (it should not be marked verified)

There are several edge cases for DUPLICATE bugs that I am not sure we should handle automatically.

For example, the duplicate leads to another duplicate that leads to another bug that is now the “Original”.   This may need cleanup (Both duplicates should point to the same Original).

Another edge case: The bug is still affected in some versions in the original  (In that case we may need to decide to mark the duplicate as “fix-optional”)  

And one more edge case: The duplicate has more versions affected than the original  (In this case we may want to check in the original whether we need to uplift a fix or mark the original bug differently)  It would be useful to expose these!
