### ISSUE TITLE
Tests should be able to run without a config.json file

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#31]

**Comment by anubnair** [comment]
@sylvestre Test should run across all the function right? It needs api_key to call the apis. Any test api_key is available? If so, we dont need to use the config.json, rather we can hard cord this.

**Comment by anoopvalluthadam** [comment]
@sylvestre <https://github.com/sylvestre>  In most of the modules getting
it from config file, instead of that we can parse it in a common place and
pass it to the methods, which will help us when we import that modules in
to some other modules.

On Thu, 22 Oct 2015 at 10:32 ANU B NAIR <notifications@github.com> wrote:

> @sylvestre <https://github.com/sylvestre> Test should run across all the
> function right? It needs api_key to call the apis. Any test api_key is
> available? If so, we dont need to use the config.json, rather we can hard
> cord this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/relman-auto-nag/issues/31#issuecomment-150106503>
> .
>
-- 

~anoop_valluthadam

**Comment by sylvestre** [comment]
I am not sure if a public api_key is available. I will ask.
For example, it is causing this failure:
https://travis-ci.org/mozilla/relman-auto-nag/builds/86781044

**Comment by sylvestre** [comment]
I asked to @globau and the api_key must remain private. However, I think we could try the solution 3.
Otherwise, we have other solutions:
```
<glob> so.. the options i see for you are:
<glob> 1. use bugzilla-dev ( bugzilla-dev.allizom.org ).  be aware your api-key may be deleted at any time as that system is periodically refreshed.  api-keys should not be public
<glob> 2.  read-only tests against production.  api-keys should still not be public
<glob> 3. unauthenticated testing
<glob> 4. self-host minimal bmo instance, unlimited testing with not api-key privacy issues
<glob> running destructive tests against production (eg. creating test bugs) is a good way to get an account disabled (this has happened before!)
<glob> running destructive tests against bugzilla-dev is ok
```

**Comment by anoopvalluthadam** [comment]
Reply for 4 points mentioned above:
---------------------------------------------------

1. If we are using  bugzilla-dev.allizom.org as API, we have to change the whole APIs in the code when testing( change the APIs to a settings file), since the APIs are not from a settings file. 

2. read-only tests against production: public API KEY!

3. unauthenticated testing: How it works for bugzilla production API or any other APIs, still we need a KEY, isn't it?

4. I didn't understand!

**Comment by anubnair** [comment]
@sylvestre : I have tried to create an api key with bugzilla-dev ( bugzilla-dev.allizom.org ) But I got "GitHub returned an error: Unauthorized  Error"

**Comment by globau** [comment]
@anoopvalluthadam 

1 & 2. something that is very common is a config file - put the hostname and the api-key into it and ensure it's never committed into the tree.

3. "unauthenticated testing" means without an api-key.  requests such as bug searching/getting will work, but you only have visibility of public bugs.

4. some other projects that need to run tests against bugzilla run all of their tests within multiple docker containers (this makes CI integration easier too). in this scenario you'd build a docker image for bmo and use that as the end-point for your testing.

@anubnair : did you ask on the #bmo irc channel for access (as per the instructions on every page)?


my recommendation is you create a config file that holds the api-key (and any other related config data for the tests).  get yourself setup on bugzilla-dev as per the header, and use bugzilla-dev for your testing.  using production may be problematic if your test suite is expanded to perform destructive tests (such as creating / updating bugs).

**Comment by sylvestre** [comment]
I think that https://github.com/anoopvalluthadam/bztools/commit/caf54aa7a4a294f5414826f2b53b60e4a9e48a04 implemented the change and I am happy with it.
