### ISSUE TITLE
The bot is confirming unconfirmed bugs

### ISSUE THREAD

**Issue by dblohm7** [mozilla/relman-auto-nag#816]
In bug 1553775, we had an unconfirmed issue. I assigned it to somebody to see if they could reproduce.

At
https://bugzilla.mozilla.org/show_bug.cgi?id=1553775#a6783743_575867
bugbug changed the status to ASSIGNED, which causes Bugzilla to set the confirmed flag to true.

I suppose this is more an issue of policy, but personally I do not think that bugbug should be changing that status away from UNCONFIRMED, as that has greater implications than changing a status away from the other states.

**Comment by Vishal19111999** [comment]
I want to solve my first bug. Should K go with this one?

**Comment by Standard8** [comment]
> I suppose this is more an issue of policy, but personally I do not think that bugbug should be changing that status away from UNCONFIRMED, as that has greater implications than changing a status away from the other states.

I agree with this. This was my case: I self-assigned a bug yesterday so that I could a) put it in my easy access-list, and b) let people know I was intending to look at it as I'd had a twitter discussion with the person who filed it and wanted to continue that relationship.

In this case I suspect it will be a confirmed bug, but it should really be a decision by someone to confirm it.

**Comment by calixteman** [comment]
@sylvestre, wdyt ?

**Comment by calixteman** [comment]
Since most of the time ASSIGNED == CONFIRMED, this tool is probably not so useful.
Anyway, we're looking at improving the bug status (thanks to @emceeaich).
I'll disable it.

**Comment by marco-c** [comment]
Duplicate of #420.
