### ISSUE TITLE
Severity nag emails list old tickets

### ISSUE THREAD

**Issue by gijsk** [mozilla/relman-auto-nag#964]
We only switched to triaging into specific severities in early May. This morning I had a nag email that included issues that haven't been touched since late March or even last year. I don't think they should be in the email.

Examples:

https://bugzilla.mozilla.org/show_bug.cgi?id=1595064
https://bugzilla.mozilla.org/show_bug.cgi?id=1604427
https://bugzilla.mozilla.org/show_bug.cgi?id=1621673

**Comment by sylvestre** [comment]
@emceeaich could you please have a look? Thanks!

**Comment by emceeaich** [comment]
The query is looking at bugs filed in the past year. Bugs filed before the switchover had a severity of `normal,` by default. 

Ways I could address this include:

1. Limit the queries to bugs filed since the start of the current release cycle. 
2. Assume the severity of any bug file between -1y and the start of the current release cycle that is `normal` is `p3`.

**Comment by emceeaich** [comment]
If I change https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/workflow/no_severity.py#L116 and https://github.com/mozilla/relman-auto-nag/blob/340d81eadedb187c0d7d070180c7917e17dc9a91/auto_nag/scripts/to_triage.py#L91 to remove `normal` that'll ignore the old bugs.

**Comment by emceeaich** [comment]
Yes, changing that removes the older tickets with severity of `normal`. There will be some tickets between early April and and May 4th because we did set the default value of severity to `--` in early April. 

I'm going to submit a PR for this and #965.
